HW_Chess solved 90%.
elena-step/elena-step-projects pull request #12
Opened 2017-08-31 17:12 UTC by elena-step

Поле шахматной доски определяется парой натуральных чисел, каждое из ко-
торых не превосходит 8: первое число — номер вертикали (при счете слева
направо), второе — номер горизонтали (при счете снизу вверх). Даны нату-
ральные числа a, b, c, d, каждое из которых не превосходит 8.

а) На поле (a, b) расположена ладья. Записать условие, при котором она угро-
жает полю (c, d).

б) На поле (a, b) расположен слон. Записать условие, при котором он угрожает
полю (c, d).

в) На поле (a, b) расположен король. Записать условие, при котором он может
одним ходом попасть на поле (c, d).

г) На поле (a, b) расположен ферзь. Записать условие, при котором он угрожа-
ет полю (c, d).

д) На поле (a, b) расположена белая пешка. Записать условие, при котором
она может одним ходом попасть на поле (c, d):
при обычном ходе;
когда она "бьет" фигуру или пешку соперника.

Примечание
Белые пешки перемещаются на доске снизу вверх.

е) На поле (a, b) расположена черная пешка. Записать условие, при котором
она может одним ходом попасть на поле (c, d):
при обычном ходе;
когда она "бьет" фигуру или пешку соперника.
Примечание
Черные пешки перемещаются на доске сверху вниз.

ж) На поле (a, b) расположен конь. Записать условие, при котором он угрожа-
ет полю (c, d).

2017-08-31 20:56 UTC, elena-step commented
Шахматы порешала. Буду дописывать тест. И доработаю ввод данных от пользователя.

2017-09-02 12:02 UTC, elena-step commented
Здравствуйте, Евгений!
Шахматы завершены, тест дописала и внесла небольшие правки в код. 
В метод, использующий Scanner, добавила close(), но проверку на предмет ошибок ввода не делала с целью экономии времени (с этим буду работать в задаче с Толстяками).
Нажала кнопку Commit вместо Commit and Push. Теперь не знаю, как "запушить" обновления. Создала новую ветку и новый Pull request #13, куда и загрузила окончательную версию.
Если не сложно - посоветуйте, как сюда "запушить". И тогда новую ветку я смогу удалить.

2017-09-02 14:00 UTC, elena-step commented
Все залила. Плюс внесла проверку во ввод данных пользователем.

2017-09-10 08:44 UTC, strazhkoe requested changes

2017-09-10 08:44 UTC, strazhkoe commented on src/javasummer2017/ChessFigures/ChessFigures.java
> +            case 1:
Числа в кейсах и в тексте сообщений пользователю нужно вынести в константы

2017-09-10 09:28 UTC, elena-step commented on src/javasummer2017/ChessFigures/ChessFigures.java
> +            case 1:
Спасибо, магические числа вынесла в константы.

2017-09-10 15:25 UTC, strazhkoe approved these changes

2017-09-10 15:25 UTC, merged