HW Foreign passport solved.
elena-step/elena-step-projects pull request #19
Opened 2017-09-15 20:25 UTC by elena-step

Создайте класс Passport, который будет содержать паспортные данные гражданина Украины. С помощью наследования (расширения), создайте класс ForeignPassport (паспорт для выезда за границу) производный от Passport. Загранпаспорт содержит данные о визах и номер загранпаспорта. Визу рекомендую реализовать как отдельный класс и типом визы и датой открытия и закрытия (плюс дополнительные свойства на ваше усмотрение)

2017-09-17 17:12 UTC, strazhkoe requested changes

2017-09-17 17:12 UTC, strazhkoe commented on src/javasummer2017/ForeignPassport/ForeignPassport.java
> +    }
Это конструктор по логике абсолютно идентичен с `public ForeignPassport(String firstName, String lastName)` Скопированного кода быть не должно

2017-09-17 17:12 UTC, strazhkoe commented on src/javasummer2017/ForeignPassport/ForeignPassport.java
> +        setForeignPassportNumber(foreignPassportNumber);
Что в данном контексте делают эти два сеттера?

2017-09-17 17:12 UTC, strazhkoe commented on src/javasummer2017/ForeignPassport/ForeignPassport.java
> +    private Visa visa;
Паспорт у нас ограничен только одной визой?

2017-09-17 17:12 UTC, strazhkoe commented on src/javasummer2017/ForeignPassport/Passport.java
> +        this.passportNumber = DEFAULT_PASSPORT_NUMBER;
вместо этих четырех строк лучше написать `this(firstName, lastName, DEFAULT_PASSOPRT_SERIAL, DEFAULT_PASSPORT_NUMBER)`

2017-09-17 17:23 UTC, elena-step commented
Евгений, эта задача также не была сделана. Загрузила на mystat с намерениями закончить на следующий день и написать Вам. Но так сложилось, что времени на занятия не выделила. Вы пошли в mystat, где загружены не решенные задачи. 





17 вересня 2017, 20:12:55, від "Yevhen Strazhko" <notifications@github.com>:


@strazhkoe requested changes on this pull request.
In src/javasummer2017/ForeignPassport/ForeignPassport.java:
> +    }
+
+    public ForeignPassport(String firstName, String lastName) {
+        super(firstName, lastName);
+        setForeignPassportSerial(foreignPassportSerial);
+        setForeignPassportNumber(foreignPassportNumber);
+        visa = new Visa();
+    }
+
+    public ForeignPassport(String firstName, String lastName,
+                           String foreignPassportSerial, String foreignPassportNumber) {
+        super(firstName, lastName);
+        setForeignPassportSerial(foreignPassportSerial);
+        setForeignPassportNumber(foreignPassportNumber);
+        visa = new Visa();
+    }
Это конструктор по логике абсолютно идентичен с public ForeignPassport(String firstName, String lastName) Скопированного кода быть не должно
In src/javasummer2017/ForeignPassport/ForeignPassport.java:
> +
+    private static final String DEFAULT_FOREIN_PASSPORT_SERIAL = "Unknown";
+    private static final String DEFAULT_FOREIGN_PASSPORT_NUMBER = DEFAULT_FOREIN_PASSPORT_SERIAL;
+
+
+    private String foreignPassportSerial;
+    private String foreignPassportNumber;
+    private Visa visa;
+
+    public ForeignPassport() {
+    }
+
+    public ForeignPassport(String firstName, String lastName) {
+        super(firstName, lastName);
+        setForeignPassportSerial(foreignPassportSerial);
+        setForeignPassportNumber(foreignPassportNumber);
Что в данном контексте делают эти два сеттера?
In src/javasummer2017/ForeignPassport/ForeignPassport.java:
> @@ -0,0 +1,57 @@
+package javasummer2017.ForeignPassport;
+
+public class ForeignPassport extends Passport {
+
+    private static final String DEFAULT_FOREIN_PASSPORT_SERIAL = "Unknown";
+    private static final String DEFAULT_FOREIGN_PASSPORT_NUMBER = DEFAULT_FOREIN_PASSPORT_SERIAL;
+
+
+    private String foreignPassportSerial;
+    private String foreignPassportNumber;
+    private Visa visa;
Паспорт у нас ограничен только одной визой?
In src/javasummer2017/ForeignPassport/Passport.java:
> +
+    private String firstName;
+    private String lastName;
+    private String passportSerial;
+    private String passportNumber;
+
+
+    public Passport() {
+
+    }
+
+    public Passport(String firstName, String lastName) {
+        this.firstName = firstName;
+        this.lastName = lastName;
+        this.passportSerial = DEFAULT_PASSPORT_SERIAL;
+        this.passportNumber = DEFAULT_PASSPORT_NUMBER;
вместо этих четырех строк лучше написать this(firstName, lastName, DEFAULT_PASSOPRT_SERIAL, DEFAULT_PASSPORT_NUMBER)
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-09-23 16:40 UTC, elena-step commented
Здравствуйте, Евгений!
Проверьте "Загранпаспорт", пожалуйста.

2017-09-23 20:34 UTC, strazhkoe approved these changes

2017-09-23 20:34 UTC, merged