Solved DZ9
elena-step/elena-step-projects pull request #2
Opened 2017-07-17 20:13 UTC by elena-step

Используя сортировку выбором, пузырька и вставки
отсортируйте массив введенный пользователем с клавиатуры
(до 4 элементов).
Вывод прогhаммы должен быть следующим:

Сортировка выбором:

Исходный массив: 8 6 4 2
1-й проход: 2 6 4 8
2-й проход: 2 4 6 8
3-й проход: 2 4 6 8

Пузырьковая сортировка:

Исходный массив: 8 6 4 2
1-й проход: 6 8 4 2
	             6 4 8 2
                     6 4 2 8
2-й проход: 4 6 2 8
                     4 2 6 8
3-й проход: 2 4 6 8

Сортировка вставками:

Исходный массив: 8 6 4 2
1-й проход: 6 8 4 2
2-й проход: 4 6 8 2
3-й проход: 2 4 6 8

2017-07-17 20:16 UTC, elena-step commented
Прошу проверить домашнее задание.

2017-07-17 20:33 UTC, strazhkoe requested changes

2017-07-17 20:33 UTC, strazhkoe commented on src/javasummer2017/ThreeSortings.java
> +            if (str.equals(sort[2])) {
Так как это взаимоисключающие условия, то лучше сделать через if...else if

2017-07-17 20:52 UTC, elena-step commented on src/javasummer2017/ThreeSortings.java
> +            if (str.equals(sort[2])) {
Изменения сделаны.

2017-07-18 06:09 UTC, strazhkoe requested changes

2017-07-18 06:09 UTC, strazhkoe commented on src/javasummer2017/ThreeSortings.java
> +import java.util.Arrays;
Лишний импорт. Он не используется

2017-07-21 11:17 UTC, strazhkoe approved these changes

2017-07-21 11:17 UTC, merged