HW Foreign Passport cloned
elena-step/elena-step-projects pull request #23
Opened 2017-09-29 13:21 UTC by elena-step

Добавить возможность глубокого клонирования загранпаспорта, описанного в одном из предыдущих ДЗ.

2017-09-29 13:23 UTC, elena-step commented
Евгений, не понимаю, почему clone() не работает. Помогите понять, что я делаю неверно, пожалуйста.

2017-10-01 18:16 UTC, strazhkoe requested changes

2017-10-01 18:16 UTC, strazhkoe commented on src/javasummer2017/ForeignPassportClone/ForeignPassport.java
> +        fpClone.visas = (Visa[]) visas.clone();
Виза - мутабильный класс. Нужно клонировать каждую.

2017-10-29 21:13 UTC, elena-step commented
Готово к проверке.

2017-11-04 14:55 UTC, strazhkoe approved these changes

2017-11-04 14:55 UTC, merged