My first html page is created.
elena-step/elena-step-projects pull request #34
Opened 2017-12-17 22:41 UTC by elena-step

Создать html страницу, в которой будут присутствовать 6 уровней заголовков и 2 параграфа (р).

2017-12-17 22:42 UTC, elena-step commented
Евгений,
см. первое задание по html.

2017-12-20 14:32 UTC, elena-step commented
Жень, в этом pull reguest - первая дом.работа по html  + резюме.

2017-12-25 07:39 UTC, strazhkoe requested changes
Старайтесь не помещать в один пул реквест 2 задания. С первым все хорошо, я бы его уже залил в мастер. Не говоря уже о том, что в реальном проекте такое не допустимо.

2017-12-25 07:39 UTC, strazhkoe commented on src/HTML/CV.html
> +<br>
Тут должно быть body

2017-12-25 07:39 UTC, strazhkoe commented on src/HTML/CV.html
> +    <i>
Лучше оборачивать любой текст в какие-либо блоки. Не хорошо, что они находятся прямо в боди. Например, каждый подраздел резюме можно поместить в блок <p>. Также, нехорошо разрывать строчные теги. Они должны идти в строку: `<i>телефон</i>`

2017-12-25 10:04 UTC, elena-step commented on src/HTML/CV.html
> +    <i>
Спасибо большое! Поправила. Теперь текст читается легче. Ваши замечания помогли - разница огромная!!!

2018-01-04 19:11 UTC, strazhkoe approved these changes

2018-01-04 19:11 UTC, merged