Solved DZ_12
elena-step/elena-step-projects pull request #5
Opened 2017-07-23 19:47 UTC by elena-step

Дата некоторого дня характеризуется тремя натуральными числами: g (год),
m (порядковый номер месяца) и n (число). По заданным g, n и m определить:
а) дату предыдущего дня;
б) дату следующего дня.

2017-07-23 19:48 UTC, elena-step commented
Евгений, проверьте домашнее задание, пожалуйста.

2017-07-24 09:45 UTC, strazhkoe requested changes

2017-07-24 09:45 UTC, strazhkoe commented on src/javasummer2017/YesterdayTomorrow.java
> +        g = m = n = 0;
Старайтесь избегать такой формы записи. Лучше инициализировать переменные сразу

```
int g = 0;
int m = 0;
int n = 0;

```

2017-07-24 09:45 UTC, strazhkoe commented on src/javasummer2017/YesterdayTomorrow.java
> +            messageOnlyNumbers();
То что в этом месте мы выходим из программы не понятно из имени метода. Нужно или System.exit вынести из метода сюда, или переименовать метод

2017-07-24 09:45 UTC, strazhkoe commented on src/javasummer2017/YesterdayTomorrow.java
> +        if (g < 1 || g > MAX_YEAR || m < 1 || m > 12 || n < 1 || n > getMaxDayInMonth(m, g)) {
Эту проверку нужно вынести в метод. Код будет читабельнее

2017-07-25 17:47 UTC, elena-step commented
О Евгений!
Спасибо за Ваши замечания! Это нужно быть счастливчиками, чтобы получить такого внимательного преподавателя!
По Вашим замечаниям провела коррекцию.
Спасибо Вам огромное!

2017-07-26 11:24 UTC, strazhkoe approved these changes

2017-07-26 11:24 UTC, merged