HW_14 solved.
elena-step/elena-step-projects pull request #6
Opened 2017-08-20 17:46 UTC by elena-step

Известна масса каждого человека из некоторой группы людей. Людей, имеющих массу более 100 кг, будем условно называть полными. Известно, что в группе есть, по крайней мере, 1 такой человек. Определить среднюю массу полных людей и среднюю массу остальных людей.

2017-08-20 17:49 UTC, elena-step commented
Hi, Eugene!
Look up my homework, please.

2017-08-20 21:11 UTC, strazhkoe requested changes

2017-08-20 21:11 UTC, strazhkoe commented on src/javasummer2017/AverageWeightPeople.java
> +                    System.exit(0);
Может тут лучше сделать continue чтобы пользователь мог исправиться?

2017-08-20 21:11 UTC, strazhkoe commented on src/javasummer2017/AverageWeightPeople.java
> +                    System.exit(0);
Не злоупотребляйте выходом из программы. Это делает трудным отладку. На практике так не делают так как перед выходом часто нужно делать какие-то завершающие операции по сохранению данных

2017-08-20 21:11 UTC, strazhkoe commented on src/javasummer2017/AverageWeightPeople.java
> +                System.exit(0);
Метод подсчета не должен общаться с пользователем

2017-08-20 21:11 UTC, strazhkoe commented on src/javasummer2017/AverageWeightPeople.java
> +                System.exit(0);
Метод подсчета не должен общаться с пользователем

2017-08-20 21:11 UTC, strazhkoe commented on src/javasummer2017/AverageWeightPeople.java
> +        }
Методы подсчетов очень похожи. Нужно избежать повторения кода.

2017-08-28 18:06 UTC, elena-step commented on src/javasummer2017/AverageWeightPeople.java
> +                    System.exit(0);
Вместо System.exit попробовала сделать continue, но программа выбрасывает исключение:
"Exception in thread "main" java.util.InputMismatchException."
А с System.exit все работает...

2017-10-08 11:52 UTC, closed without merging