Recursion solded.
elena-step/elena-step-projects pull request #8
Opened 2017-08-21 09:11 UTC by elena-step

Написать рекурсивную процедуру для вывода на экран цифр натурального числа в обратном порядке.

2017-08-21 09:14 UTC, elena-step commented
Здравствуйте, Евгений!
Задача с рекурсией ждет Вашей проверки.

2017-08-23 13:05 UTC, strazhkoe requested changes

2017-08-23 13:05 UTC, strazhkoe commented on src/javasummer2017/ReverseNaturalNumber.java
> +            System.exit(0);
Подумайте как убрать `System.exit(0);`

2017-08-23 13:05 UTC, strazhkoe commented on src/javasummer2017/ReverseNaturalNumber.java
> +    private static void reverseNaturalNumber(int naturalNumber) {
метод должен вернуть результат, а не вывести его на экран

2017-10-08 11:53 UTC, closed without merging