"Deposit" is located in a new branch
elena-step/elena-step-projects pull request #9
Opened 2017-08-21 11:40 UTC by elena-step

Гражданин открыл счет в банке, положив 1000 USD. Через каждый месяц размер вклада увеличивается на 2% от имеющейся суммы. Определить:
a) на какой месяц величина ежемесячного увеличения вклада превысит 30 USD;
б) через сколько месяцев размер вклада превысит 1200 USD.

2017-08-21 11:43 UTC, elena-step commented
Создала новую ветку для Депозита (классная работа). Спасибо!

2017-08-23 13:03 UTC, strazhkoe requested changes

2017-08-23 13:03 UTC, strazhkoe commented on src/javasummer2017/Deposit.java
> +        Scanner scan = new Scanner(System.in);
Если сканер открывается каждый раз при вызове метода, то его в конце метода нужно закрывать `scan.close()`

2017-08-23 13:03 UTC, strazhkoe commented on src/javasummer2017/Deposit.java
> +        System.out.printf("%.2f", data);
вместо последующего вызова System.out.println() можно добавить %n здесь (%.2f%n)

2017-08-28 20:09 UTC, elena-step commented on src/javasummer2017/Deposit.java
> +        Scanner scan = new Scanner(System.in);
Метод не хочет работать, когда я написала scan.close( ) в конце метода.

2017-08-28 20:20 UTC, elena-step commented
Может, переписать ввод данных от пользователя через сканирование строки?

2017-10-08 11:58 UTC, strazhkoe approved these changes

2017-10-08 11:58 UTC, merged